# Uncomment this line to define a global platform for your project
platform :ios, '11.4'
use_frameworks!

target 'Example' do

pod 'IGRPhotoTweaks', :path => '../'
pod 'HorizontalDial', :git => 'https://github.com/iKorich/HorizontalDial.git'

end

