# Uncomment this line to define a global platform for your project
platform :ios, '10.3'
use_frameworks!

source "https://github.com/CocoaPods/Specs.git"

pod 'IGRPhotoTweaks', :path => '../'
pod 'HorizontalDial', :git => 'https://github.com/iKorich/HorizontalDial.git'

target 'Example' do
end

target 'ExampleObjC' do
end
